# Generated by Django 3.0.8 on 2020-07-29 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200728_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='first_text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
