# Generated by Django 3.0.8 on 2020-07-29 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200728_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category_tags',
            field=models.CharField(choices=[('travel', 'Travel'), ('fashion', 'Fashion'), ('technology', 'Technology'), ('food', 'Food'), ('photography', 'Photography')], max_length=15, null=True),
        ),
    ]
