# Generated by Django 3.0.8 on 2020-07-29 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_post_category_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='intro_picture',
            field=models.ImageField(default='default.jpg', upload_to='blog_post_images'),
        ),
    ]
