# Generated by Django 3.0.8 on 2020-07-30 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_post_intro_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hyperlink',
            field=models.URLField(null=True),
        ),
    ]
