# Generated by Django 3.0.8 on 2020-07-30 01:22

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_post_hyperlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category_tags',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('travel', 'Travel'), ('fashion', 'Fashion'), ('technology', 'Technology'), ('food', 'Food'), ('photography', 'Photography')], max_length=42, null=True),
        ),
    ]
