# Generated by Django 3.0.8 on 2020-08-03 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20200801_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='blog.Comment'),
        ),
        migrations.AlterField(
            model_name='post',
            name='intro_picture',
            field=models.ImageField(default='default.png', upload_to='blog_post_images'),
        ),
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.ImageField(default='default.png', upload_to='blog_post_images'),
        ),
    ]
