# Generated by Django 3.0.8 on 2020-08-06 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_auto_20200806_1547'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
