# Generated by Django 3.0.8 on 2020-08-08 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_auto_20200807_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='fashion_count',
        ),
        migrations.RemoveField(
            model_name='category',
            name='food_count',
        ),
        migrations.RemoveField(
            model_name='category',
            name='photography_count',
        ),
        migrations.RemoveField(
            model_name='category',
            name='technology_count',
        ),
        migrations.RemoveField(
            model_name='category',
            name='travel_count',
        ),
        migrations.AddField(
            model_name='post',
            name='fashion_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='food_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='photography_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='technology_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='travel_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
