# Generated by Django 3.0.8 on 2020-08-09 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_auto_20200808_0022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='fashion_count',
        ),
        migrations.RemoveField(
            model_name='post',
            name='food_count',
        ),
        migrations.RemoveField(
            model_name='post',
            name='photography_count',
        ),
        migrations.RemoveField(
            model_name='post',
            name='technology_count',
        ),
        migrations.RemoveField(
            model_name='post',
            name='travel_count',
        ),
        migrations.AlterField(
            model_name='post',
            name='category_tags',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='blog.Category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='view_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
