# Generated by Django 3.0.8 on 2020-08-12 02:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0033_popular_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='popular_article',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
