# Generated by Django 3.0.8 on 2020-08-15 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_popular_article_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='intro_picture',
            field=models.ImageField(default='default.jpg', upload_to='blog_post_images'),
        ),
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.ImageField(default='default.jpg', upload_to='blog_post_images'),
        ),
    ]
