# Generated by Django 3.0.8 on 2020-08-16 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0035_auto_20200815_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='hyperlink',
        ),
        migrations.AddField(
            model_name='post',
            name='photo_by',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
